site_name: Nexus Plugin Components Documentation
site_url: https://thenexusavenger.github.io/Nexus-Plugin-Components
repo_name: TheNexusAvenger/Nexus-Plugin-Components
repo_url: https://github.com/TheNexusAvenger/Nexus-Plugin-Components

theme:
  name: 'material'
  palette:
    primary: 'Blue'
    accent: 'Light Blue'

nav:
  - Home: index.md
  - Examples:
    - Noraml Instances: examples/normal-instances.md
    - Lists: examples/lists.md

markdown_extensions:
  - admonition
  - codehilite