[package]
name = "thenexusavenger/nexus-plugin-components"
repository = "https://github.com/TheNexusAvenger/Nexus-Plugin-Components"
description = "Helper components for developing plugins in Roblox Studio."
license = "MIT"
authors = ["TheNexusAvenger"]
version = "1.2.0"

registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["dist", "dist/*", "src", "src/*", "default.project.json", "wally.lock", "wally.toml"]

[dependencies]
Fusion = "elttob/fusion@0.3.0"
NexusVirtualList = "thenexusavenger/nexus-virtual-list@1.1.0"